import Link from 'next/link';

export default function SqlFormatterPostEn() {
  return (
    <article className="prose prose-gray dark:prose-invert max-w-none">
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">Formatter · July 7, 2026 · 4 min read</p>

      <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
        SQL Generated by Your ORM Is Unreadable. Here's How to Quickly Format It
      </h1>

      <p className="mb-4">
        <Link href="/en/tools/sql-formatter-en" className="inline-flex items-center gap-1 text-blue-600 dark:text-blue-400 font-medium hover:underline">
          👉 Try the SQL Formatter
        </Link>
      </p>

      <blockquote className="border-l-4 border-blue-500 pl-4 italic text-gray-600 dark:text-gray-400 mb-6">
        Copied the raw SQL from the ORM query log to debug a performance issue. It was all on one line with inconsistent capitalization. Spent ten minutes just formatting it before I could start investigating.
      </blockquote>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">When SQL Formatting Actually Matters</h2>

      <p className="mb-3">More situations than you'd think:</p>

      <ul className="space-y-1 mb-4 text-gray-700 dark:text-gray-300">
        <li>ORM-generated queries → usually minified and lowercase, hard to follow</li>
        <li>Query log analysis → production logs strip formatting</li>
        <li>Copying from BI tools → Tableau, Looker, Metabase generate their own style</li>
        <li>Code review → unformatted SQL in a PR is painful to read</li>
        <li>Documentation → example queries should be readable</li>
        <li>Performance tuning → need to see JOIN structure and subqueries clearly</li>
        <li>Migrating queries between databases → easier to spot dialect-specific syntax</li>
      </ul>

      <p className="mb-4">
        SQL formatting is lower stakes than SQL correctness, but it has a real impact on how quickly you can understand what a query is doing. A well-formatted 30-line query is comprehensible at a glance. The same query as one unindented block makes you trace through it manually.
      </p>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Why Not Just Use the Database Client?</h2>

      <ul className="space-y-1 mb-4 text-gray-700 dark:text-gray-300">
        <li>pgAdmin, DBeaver, DataGrip → have formatters, but you need them open and connected</li>
        <li>VS Code SQL extensions → work, but require the extension and a file</li>
        <li>Online formatters → many exist, but most have ads and slow page loads</li>
        <li>Manual formatting → tedious and inconsistent across team members</li>
      </ul>

      <p className="mb-4">
        A quick browser-based formatter is useful when you're working with a query string outside of a database client — in a Slack message, a log file, a code review, a ticket. You just want to paste and read.
      </p>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">What the Tool Does</h2>

      <p className="mb-3">Core features:</p>

      <ul className="space-y-1 mb-4 text-gray-700 dark:text-gray-300">
        <li>Formats SQL with consistent indentation and line breaks</li>
        <li>Uppercases SQL keywords (SELECT, FROM, WHERE, JOIN, etc.)</li>
        <li>Aligns clauses for readability</li>
        <li>Handles subqueries with proper nested indentation</li>
        <li>Supports common SQL dialects: MySQL, PostgreSQL, SQL Server, SQLite</li>
        <li>Minification mode (remove whitespace for compact logging)</li>
      </ul>

      <p className="mb-3">Nice to have:</p>

      <ul className="space-y-1 mb-4 text-gray-700 dark:text-gray-300">
        <li>Syntax highlighting for keywords, strings, numbers, comments</li>
        <li>Copy button</li>
        <li>Indentation size preference</li>
        <li>Keyword case option (UPPERCASE, lowercase, Capitalize)</li>
      </ul>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">SQL Formatting Conventions That Help Readability</h2>

      <p className="mb-4">
        There's no single official SQL style guide, but there are conventions that most teams converge on:
      </p>

      <p className="mb-4">
        Keywords in uppercase: <code>SELECT</code>, <code>FROM</code>, <code>WHERE</code>, <code>GROUP BY</code>, <code>ORDER BY</code>. This makes the structure of the query immediately visible even in a long block.
      </p>

      <p className="mb-4">
        One clause per line, with the keyword left-aligned or right-aligned (teams pick one and stick with it). Subqueries indented inside their parent clause. JOINs on their own lines with the ON condition on the next line. Column lists broken one per line for wide SELECTs.
      </p>

      <p className="mb-4">
        CTEs (Common Table Expressions, the <code>WITH</code> clause) deserve particular care — each CTE gets its own named block, indented inside the <code>WITH</code>. The final SELECT then reads like a simple query against named virtual tables. Well-formatted CTEs are often clearer than an equivalent set of nested subqueries.
      </p>

      <p className="mb-4">
        Comments matter too. SQL supports both line comments (<code>--</code>) and block comments (<code>/* */</code>). Explaining why a particular filter or join is there is often more valuable than explaining what it does.
      </p>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Honest Assessment</h2>

      <p className="mb-2 font-medium text-gray-800 dark:text-gray-200">What works well:</p>
      <ul className="space-y-1 mb-4 text-gray-700 dark:text-gray-300">
        <li>ORM-generated query soup becomes readable in one paste</li>
        <li>Keyword uppercasing and indentation are consistent</li>
        <li>Works with most standard SQL — SELECT, INSERT, UPDATE, DELETE, CTEs</li>
      </ul>

      <p className="mb-2 font-medium text-gray-800 dark:text-gray-200">Limitations:</p>
      <ul className="space-y-1 mb-4 text-gray-700 dark:text-gray-300">
        <li>Dialect-specific extensions (CONNECT BY, MERGE, PIVOT) may not format perfectly</li>
        <li>Very complex queries with deep nesting can sometimes produce imperfect indentation</li>
        <li>No query validation or execution</li>
      </ul>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">How to Use It</h2>

      <ol className="space-y-1 mb-4 text-gray-700 dark:text-gray-300 list-decimal list-inside">
        <li>Paste your SQL query into the input area</li>
        <li>Pick your dialect and formatting preferences</li>
        <li>Get back cleanly formatted SQL instantly</li>
        <li>Copy and use it wherever you need it</li>
      </ol>

      <p className="mb-4">Takes seconds regardless of query complexity.</p>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Try It</h2>

      <p className="mb-4">
        <Link href="/en/tools/sql-formatter-en" className="inline-flex items-center gap-1 text-blue-600 dark:text-blue-400 font-medium hover:underline">
          👉 Try the SQL Formatter
        </Link>
      </p>

      <p className="text-gray-600 dark:text-gray-400">Browser-based. No database connection needed.</p>

      <hr className="border-gray-200 dark:border-gray-700 my-6" />

      <p className="text-sm text-gray-500 dark:text-gray-400">
        `#sql-formatter` `#sql-beautifier` `#sql-tools` `#developer-tools` `#database`
      </p>
    </article>
  );
}
