import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

// 도구 컴포넌트 레지스트리 (Dynamic Import - 코드 스플리팅)
// 각 도구는 필요할 때만 로드됨

const toolComponents: Record<string, ComponentType> = {
  // 텍스트 도구
  'character-counter': dynamic(() => import('./text/CharacterCounter').then(m => ({ default: m.CharacterCounter }))),
  'case-converter': dynamic(() => import('./text/CaseConverter').then(m => ({ default: m.CaseConverter }))),
  'line-break-remover': dynamic(() => import('./text/LineBreakRemover').then(m => ({ default: m.LineBreakRemover }))),
  'duplicate-line-remover': dynamic(() => import('./text/DuplicateLineRemover').then(m => ({ default: m.DuplicateLineRemover }))),
  'text-sorter': dynamic(() => import('./text/TextSorter').then(m => ({ default: m.TextSorter }))),
  'random-string-generator': dynamic(() => import('./text/RandomStringGenerator').then(m => ({ default: m.RandomStringGenerator }))),
  'korean-english-converter': dynamic(() => import('./text/KoreanEnglishConverter').then(m => ({ default: m.KoreanEnglishConverter }))),
  'lorem-ipsum': dynamic(() => import('./text/LoremIpsum').then(m => ({ default: m.LoremIpsum }))),
  'text-diff': dynamic(() => import('./text/TextDiff').then(m => ({ default: m.TextDiff }))),
  'word-frequency': dynamic(() => import('./text/WordFrequency').then(m => ({ default: m.WordFrequency }))),
  'message-length-checker': dynamic(() => import('./text/MessageLengthChecker').then(m => ({ default: m.MessageLengthChecker }))),
  'reading-time-calculator': dynamic(() => import('./text/ReadingTimeCalculator').then(m => ({ default: m.ReadingTimeCalculator }))),
  'character-counter-en': dynamic(() => import('./text/CharacterCounterEn').then(m => ({ default: m.CharacterCounterEn }))),
  'case-converter-en': dynamic(() => import('./text/CaseConverterEn').then(m => ({ default: m.CaseConverterEn }))),
  'line-break-remover-en': dynamic(() => import('./text/LineBreakRemoverEn').then(m => ({ default: m.LineBreakRemoverEn }))),
  'duplicate-line-remover-en': dynamic(() => import('./text/DuplicateLineRemoverEn').then(m => ({ default: m.DuplicateLineRemoverEn }))),
  'text-sorter-en': dynamic(() => import('./text/TextSorterEn').then(m => ({ default: m.TextSorterEn }))),
  'random-string-generator-en': dynamic(() => import('./text/RandomStringGeneratorEn').then(m => ({ default: m.RandomStringGeneratorEn }))),
  'lorem-ipsum-en': dynamic(() => import('./text/LoremIpsumEn').then(m => ({ default: m.LoremIpsumEn }))),
  'text-diff-en': dynamic(() => import('./text/TextDiffEn').then(m => ({ default: m.TextDiffEn }))),
  'word-frequency-en': dynamic(() => import('./text/WordFrequencyEn').then(m => ({ default: m.WordFrequencyEn }))),
  'message-length-checker-en': dynamic(() => import('./text/MessageLengthCheckerEn').then(m => ({ default: m.MessageLengthCheckerEn }))),
  'reading-time-calculator-en': dynamic(() => import('./text/ReadingTimeCalculatorEn').then(m => ({ default: m.ReadingTimeCalculatorEn }))),
  'regex-generator': dynamic(() => import('./text/RegexGenerator').then(m => ({ default: m.RegexGenerator }))),
  'regex-generator-en': dynamic(() => import('./text/RegexGeneratorEn').then(m => ({ default: m.RegexGeneratorEn }))),
  'line-number': dynamic(() => import('./text/LineNumber').then(m => ({ default: m.LineNumber }))),
  'line-number-en': dynamic(() => import('./text/LineNumberEn').then(m => ({ default: m.LineNumberEn }))),

  // 인코딩/디코딩
  'base64': dynamic(() => import('./encoding/Base64Tool').then(m => ({ default: m.Base64Tool }))),
  'url-encoder': dynamic(() => import('./encoding/UrlEncoder').then(m => ({ default: m.UrlEncoder }))),
  'hash-generator': dynamic(() => import('./encoding/HashGenerator').then(m => ({ default: m.HashGenerator }))),
  'html-entity': dynamic(() => import('./encoding/HtmlEntity').then(m => ({ default: m.HtmlEntity }))),
  'unicode-converter': dynamic(() => import('./encoding/UnicodeConverter').then(m => ({ default: m.UnicodeConverter }))),
  'morse-code': dynamic(() => import('./encoding/MorseCode').then(m => ({ default: m.MorseCode }))),
  'jwt-decoder': dynamic(() => import('./encoding/JwtDecoder').then(m => ({ default: m.JwtDecoder }))),
  'base64-en': dynamic(() => import('./encoding/Base64ToolEn').then(m => ({ default: m.Base64ToolEn }))),
  'url-encoder-en': dynamic(() => import('./encoding/UrlEncoderEn').then(m => ({ default: m.UrlEncoderEn }))),
  'hash-generator-en': dynamic(() => import('./encoding/HashGeneratorEn').then(m => ({ default: m.HashGeneratorEn }))),
  'html-entity-en': dynamic(() => import('./encoding/HtmlEntityEn').then(m => ({ default: m.HtmlEntityEn }))),
  'unicode-converter-en': dynamic(() => import('./encoding/UnicodeConverterEn').then(m => ({ default: m.UnicodeConverterEn }))),
  'morse-code-en': dynamic(() => import('./encoding/MorseCodeEn').then(m => ({ default: m.MorseCodeEn }))),
  'jwt-decoder-en': dynamic(() => import('./encoding/JwtDecoderEn').then(m => ({ default: m.JwtDecoderEn }))),
  'string-escape': dynamic(() => import('./encoding/StringEscape').then(m => ({ default: m.StringEscape }))),
  'string-escape-en': dynamic(() => import('./encoding/StringEscapeEn').then(m => ({ default: m.StringEscapeEn }))),

  // 포맷터
  'json-formatter': dynamic(() => import('./formatter/JsonFormatter').then(m => ({ default: m.JsonFormatter }))),
  'json-csv-converter': dynamic(() => import('./formatter/JsonCsvConverter').then(m => ({ default: m.JsonCsvConverter }))),
  'xml-formatter': dynamic(() => import('./formatter/XmlFormatter').then(m => ({ default: m.XmlFormatter }))),
  'sql-formatter': dynamic(() => import('./formatter/SqlFormatter').then(m => ({ default: m.SqlFormatter }))),
  'minifier': dynamic(() => import('./formatter/Minifier').then(m => ({ default: m.Minifier }))),
  'markdown-preview': dynamic(() => import('./formatter/MarkdownPreview').then(m => ({ default: m.MarkdownPreview }))),
  'yaml-json-converter': dynamic(() => import('./formatter/YamlJsonConverter').then(m => ({ default: m.YamlJsonConverter }))),
  'url-query-parser': dynamic(() => import('./formatter/UrlQueryParser').then(m => ({ default: m.UrlQueryParser }))),
  'json-formatter-en': dynamic(() => import('./formatter/JsonFormatterEn').then(m => ({ default: m.JsonFormatterEn }))),
  'json-csv-converter-en': dynamic(() => import('./formatter/JsonCsvConverterEn').then(m => ({ default: m.JsonCsvConverterEn }))),
  'xml-formatter-en': dynamic(() => import('./formatter/XmlFormatterEn').then(m => ({ default: m.XmlFormatterEn }))),
  'sql-formatter-en': dynamic(() => import('./formatter/SqlFormatterEn').then(m => ({ default: m.SqlFormatterEn }))),
  'minifier-en': dynamic(() => import('./formatter/MinifierEn').then(m => ({ default: m.MinifierEn }))),
  'markdown-preview-en': dynamic(() => import('./formatter/MarkdownPreviewEn').then(m => ({ default: m.MarkdownPreviewEn }))),
  'yaml-json-converter-en': dynamic(() => import('./formatter/YamlJsonConverterEn').then(m => ({ default: m.YamlJsonConverterEn }))),
  'url-query-parser-en': dynamic(() => import('./formatter/UrlQueryParserEn').then(m => ({ default: m.UrlQueryParserEn }))),
  'html-preview': dynamic(() => import('./formatter/HtmlPreview').then(m => ({ default: m.HtmlPreview }))),
  'html-preview-en': dynamic(() => import('./formatter/HtmlPreviewEn').then(m => ({ default: m.HtmlPreviewEn }))),
  'code-diff': dynamic(() => import('./formatter/CodeDiff').then(m => ({ default: m.CodeDiff }))),
  'code-diff-en': dynamic(() => import('./formatter/CodeDiffEn').then(m => ({ default: m.CodeDiffEn }))),
  'cron-parser': dynamic(() => import('./formatter/CronParser').then(m => ({ default: m.CronParser }))),
  'cron-parser-en': dynamic(() => import('./formatter/CronParserEn').then(m => ({ default: m.CronParserEn }))),
  'http-status-code': dynamic(() => import('./formatter/HttpStatusCode').then(m => ({ default: m.HttpStatusCode }))),
  'http-status-code-en': dynamic(() => import('./formatter/HttpStatusCodeEn').then(m => ({ default: m.HttpStatusCodeEn }))),
  'json-path-tester': dynamic(() => import('./formatter/JsonPathTester').then(m => ({ default: m.JsonPathTester }))),
  'json-path-tester-en': dynamic(() => import('./formatter/JsonPathTesterEn').then(m => ({ default: m.JsonPathTesterEn }))),
  'html-boilerplate': dynamic(() => import('./formatter/HtmlBoilerplate').then(m => ({ default: m.HtmlBoilerplate }))),
  'html-boilerplate-en': dynamic(() => import('./formatter/HtmlBoilerplateEn').then(m => ({ default: m.HtmlBoilerplateEn }))),
  'flexbox-playground': dynamic(() => import('./formatter/FlexboxPlayground').then(m => ({ default: m.FlexboxPlayground }))),
  'flexbox-playground-en': dynamic(() => import('./formatter/FlexboxPlaygroundEn').then(m => ({ default: m.FlexboxPlaygroundEn }))),
  'og-preview': dynamic(() => import('./formatter/OgPreview').then(m => ({ default: m.OgPreview }))),
  'og-preview-en': dynamic(() => import('./formatter/OgPreviewEn').then(m => ({ default: m.OgPreviewEn }))),
  'mermaid-diagram': dynamic(() => import('./formatter/MermaidDiagram').then(m => ({ default: m.MermaidDiagram }))),
  'mermaid-diagram-en': dynamic(() => import('./formatter/MermaidDiagramEn').then(m => ({ default: m.MermaidDiagramEn }))),

  // 이미지 도구
  'image-resize': dynamic(() => import('./image/ImageResize').then(m => ({ default: m.ImageResize }))),
  'image-compress': dynamic(() => import('./image/ImageCompress').then(m => ({ default: m.ImageCompress }))),
  'image-convert': dynamic(() => import('./image/ImageConvert').then(m => ({ default: m.ImageConvert }))),
  'image-crop': dynamic(() => import('./image/ImageCrop').then(m => ({ default: m.ImageCrop }))),
  'image-rotate': dynamic(() => import('./image/ImageRotate').then(m => ({ default: m.ImageRotate }))),
  'base64-image': dynamic(() => import('./image/Base64Image').then(m => ({ default: m.Base64Image }))),
  'favicon-generator': dynamic(() => import('./image/FaviconGenerator').then(m => ({ default: m.FaviconGenerator }))),
  'video-gif-converter': dynamic(() => import('./image/VideoGifConverter').then(m => ({ default: m.VideoGifConverter }))),
  'image-resize-en': dynamic(() => import('./image/ImageResizeEn').then(m => ({ default: m.ImageResizeEn }))),
  'image-compress-en': dynamic(() => import('./image/ImageCompressEn').then(m => ({ default: m.ImageCompressEn }))),
  'image-convert-en': dynamic(() => import('./image/ImageConvertEn').then(m => ({ default: m.ImageConvertEn }))),
  'image-crop-en': dynamic(() => import('./image/ImageCropEn').then(m => ({ default: m.ImageCropEn }))),
  'image-rotate-en': dynamic(() => import('./image/ImageRotateEn').then(m => ({ default: m.ImageRotateEn }))),
  'base64-image-en': dynamic(() => import('./image/Base64ImageEn').then(m => ({ default: m.Base64ImageEn }))),
  'favicon-generator-en': dynamic(() => import('./image/FaviconGeneratorEn').then(m => ({ default: m.FaviconGeneratorEn }))),
  'video-gif-converter-en': dynamic(() => import('./image/VideoGifConverterEn').then(m => ({ default: m.VideoGifConverterEn }))),

  // 색상 도구
  'color-converter': dynamic(() => import('./color/ColorConverter').then(m => ({ default: m.ColorConverter }))),
  'palette-generator': dynamic(() => import('./color/PaletteGenerator').then(m => ({ default: m.PaletteGenerator }))),
  'gradient-generator': dynamic(() => import('./color/GradientGenerator').then(m => ({ default: m.GradientGenerator }))),
  'contrast-checker': dynamic(() => import('./color/ContrastChecker').then(m => ({ default: m.ContrastChecker }))),
  'image-color-picker': dynamic(() => import('./color/ImageColorPicker').then(m => ({ default: m.ImageColorPicker }))),
  'color-blender': dynamic(() => import('./color/ColorBlender').then(m => ({ default: m.ColorBlender }))),
  'color-blind-simulator': dynamic(() => import('./color/ColorBlindSimulator').then(m => ({ default: m.ColorBlindSimulator }))),
  'color-converter-en': dynamic(() => import('./color/ColorConverterEn').then(m => ({ default: m.ColorConverterEn }))),
  'palette-generator-en': dynamic(() => import('./color/PaletteGeneratorEn').then(m => ({ default: m.PaletteGeneratorEn }))),
  'gradient-generator-en': dynamic(() => import('./color/GradientGeneratorEn').then(m => ({ default: m.GradientGeneratorEn }))),
  'contrast-checker-en': dynamic(() => import('./color/ContrastCheckerEn').then(m => ({ default: m.ContrastCheckerEn }))),
  'image-color-picker-en': dynamic(() => import('./color/ImageColorPickerEn').then(m => ({ default: m.ImageColorPickerEn }))),
  'color-blender-en': dynamic(() => import('./color/ColorBlenderEn').then(m => ({ default: m.ColorBlenderEn }))),
  'color-blind-simulator-en': dynamic(() => import('./color/ColorBlindSimulatorEn').then(m => ({ default: m.ColorBlindSimulatorEn }))),
  'box-shadow-generator': dynamic(() => import('./color/BoxShadowGenerator').then(m => ({ default: m.BoxShadowGenerator }))),
  'box-shadow-generator-en': dynamic(() => import('./color/BoxShadowGeneratorEn').then(m => ({ default: m.BoxShadowGeneratorEn }))),
  'border-radius-generator': dynamic(() => import('./color/BorderRadiusGenerator').then(m => ({ default: m.BorderRadiusGenerator }))),
  'border-radius-generator-en': dynamic(() => import('./color/BorderRadiusGeneratorEn').then(m => ({ default: m.BorderRadiusGeneratorEn }))),

  // 계산기/생성기
  'uuid-generator': dynamic(() => import('./calculator/UuidGenerator').then(m => ({ default: m.UuidGenerator }))),
  'qr-generator': dynamic(() => import('./calculator/QrGenerator').then(m => ({ default: m.QrGenerator }))),
  'date-calculator': dynamic(() => import('./calculator/DateCalculator').then(m => ({ default: m.DateCalculator }))),
  'percentage': dynamic(() => import('./calculator/PercentageCalculator').then(m => ({ default: m.PercentageCalculator }))),
  'base-converter': dynamic(() => import('./calculator/BaseConverter').then(m => ({ default: m.BaseConverter }))),
  'unix-timestamp': dynamic(() => import('./calculator/UnixTimestamp').then(m => ({ default: m.UnixTimestamp }))),
  'unit-converter': dynamic(() => import('./calculator/UnitConverter').then(m => ({ default: m.UnitConverter }))),
  'regex-tester': dynamic(() => import('./calculator/RegexTester').then(m => ({ default: m.RegexTester }))),
  'timer': dynamic(() => import('./calculator/Timer').then(m => ({ default: m.Timer }))),
  'server-time': dynamic(() => import('./calculator/ServerTime').then(m => ({ default: m.ServerTime }))),
  'server-time-en': dynamic(() => import('./calculator/ServerTimeEn').then(m => ({ default: m.ServerTimeEn }))),
  'ratio-calculator': dynamic(() => import('./calculator/RatioCalculator').then(m => ({ default: m.RatioCalculator }))),
  'age-calculator': dynamic(() => import('./calculator/AgeCalculator').then(m => ({ default: m.AgeCalculator }))),
  'bmi-calculator': dynamic(() => import('./calculator/BmiCalculator').then(m => ({ default: m.BmiCalculator }))),
  'random-picker': dynamic(() => import('./calculator/RandomPicker').then(m => ({ default: m.RandomPicker }))),
  'meeting-cost-calculator': dynamic(() => import('./calculator/MeetingCostCalculator').then(m => ({ default: m.MeetingCostCalculator }))),
  'meeting-cost-calculator-en': dynamic(() => import('./calculator/MeetingCostCalculatorEn').then(m => ({ default: m.MeetingCostCalculatorEn }))),
  'css-unit-converter': dynamic(() => import('./calculator/CssUnitConverter').then(m => ({ default: m.CssUnitConverter }))),
  'bmi-calculator-en': dynamic(() => import('./calculator/BmiCalculatorEn').then(m => ({ default: m.BmiCalculatorEn }))),
  'ratio-calculator-en': dynamic(() => import('./calculator/RatioCalculatorEn').then(m => ({ default: m.RatioCalculatorEn }))),
  'timer-en': dynamic(() => import('./calculator/TimerEn').then(m => ({ default: m.TimerEn }))),
  'unit-converter-en': dynamic(() => import('./calculator/UnitConverterEn').then(m => ({ default: m.UnitConverterEn }))),
  'unix-timestamp-en': dynamic(() => import('./calculator/UnixTimestampEn').then(m => ({ default: m.UnixTimestampEn }))),
  'date-calculator-en': dynamic(() => import('./calculator/DateCalculatorEn').then(m => ({ default: m.DateCalculatorEn }))),
  'percentage-en': dynamic(() => import('./calculator/PercentageCalculatorEn').then(m => ({ default: m.PercentageCalculatorEn }))),
  'random-picker-en': dynamic(() => import('./calculator/RandomPickerEn').then(m => ({ default: m.RandomPickerEn }))),
  'base-converter-en': dynamic(() => import('./calculator/BaseConverterEn').then(m => ({ default: m.BaseConverterEn }))),
  'regex-tester-en': dynamic(() => import('./calculator/RegexTesterEn').then(m => ({ default: m.RegexTesterEn }))),
  'qr-generator-en': dynamic(() => import('./calculator/QrGeneratorEn').then(m => ({ default: m.QrGeneratorEn }))),
  'uuid-generator-en': dynamic(() => import('./calculator/UuidGeneratorEn').then(m => ({ default: m.UuidGeneratorEn }))),
  'css-unit-converter-en': dynamic(() => import('./calculator/CssUnitConverterEn').then(m => ({ default: m.CssUnitConverterEn }))),
  'ip-lookup': dynamic(() => import('./calculator/IpLookup').then(m => ({ default: m.IpLookup }))),
  'ip-lookup-en': dynamic(() => import('./calculator/IpLookupEn').then(m => ({ default: m.IpLookupEn }))),
  'file-size-calculator': dynamic(() => import('./calculator/FileSizeCalculator').then(m => ({ default: m.FileSizeCalculator }))),
  'file-size-calculator-en': dynamic(() => import('./calculator/FileSizeCalculatorEn').then(m => ({ default: m.FileSizeCalculatorEn }))),
  'speed-test': dynamic(() => import('./calculator/SpeedTest').then(m => ({ default: m.SpeedTest }))),
  'speed-test-en': dynamic(() => import('./calculator/SpeedTestEn').then(m => ({ default: m.SpeedTestEn }))),
  'fake-data-generator': dynamic(() => import('./calculator/FakeDataGenerator').then(m => ({ default: m.FakeDataGenerator }))),
  'fake-data-generator-en': dynamic(() => import('./calculator/FakeDataGeneratorEn').then(m => ({ default: m.FakeDataGeneratorEn }))),
  'salary-calculator': dynamic(() => import('./calculator/SalaryCalculator').then(m => ({ default: m.SalaryCalculator }))),
  'loan-calculator': dynamic(() => import('./calculator/LoanCalculator').then(m => ({ default: m.LoanCalculator }))),
  'loan-calculator-en': dynamic(() => import('./calculator/LoanCalculatorEn').then(m => ({ default: m.LoanCalculatorEn }))),
  'interest-calculator': dynamic(() => import('./calculator/InterestCalculator').then(m => ({ default: m.InterestCalculator }))),
  'interest-calculator-en': dynamic(() => import('./calculator/InterestCalculatorEn').then(m => ({ default: m.InterestCalculatorEn }))),

  // 재미/테스트
  'reaction-time-test': dynamic(() => import('./fun/ReactionTimeTest').then(m => ({ default: m.ReactionTimeTest }))),
  'lotto-generator': dynamic(() => import('./fun/LottoGenerator').then(m => ({ default: m.LottoGenerator }))),
  'nickname-generator': dynamic(() => import('./fun/NicknameGenerator').then(m => ({ default: m.NicknameGenerator }))),
  'color-perception-test': dynamic(() => import('./fun/ColorPerceptionTest').then(m => ({ default: m.ColorPerceptionTest }))),
  'color-perception-test-en': dynamic(() => import('./fun/ColorPerceptionTestEn').then(m => ({ default: m.ColorPerceptionTestEn }))),
  'roulette-selector': dynamic(() => import('./fun/RouletteSelector').then(m => ({ default: m.RouletteSelector }))),
  'roulette-selector-en': dynamic(() => import('./fun/RouletteSelectorEn').then(m => ({ default: m.RouletteSelectorEn }))),
  'ladder-game': dynamic(() => import('./fun/LadderGame').then(m => ({ default: m.LadderGame }))),
  'ladder-game-en': dynamic(() => import('./fun/LadderGameEn').then(m => ({ default: m.LadderGameEn }))),
  'timing-test': dynamic(() => import('./fun/TimingTest').then(m => ({ default: m.TimingTest }))),
  'timing-test-en': dynamic(() => import('./fun/TimingTestEn').then(m => ({ default: m.TimingTestEn }))),
  'random-decision-maker': dynamic(() => import('./fun/RandomDecisionMaker').then(m => ({ default: m.RandomDecisionMaker }))),
  'random-decision-maker-en': dynamic(() => import('./fun/RandomDecisionMakerEn').then(m => ({ default: m.RandomDecisionMakerEn }))),
  'fortune-cookie': dynamic(() => import('./fun/FortuneCookie').then(m => ({ default: m.FortuneCookie }))),
  'order-picker': dynamic(() => import('./fun/OrderPicker').then(m => ({ default: m.OrderPicker }))),
  'order-picker-en': dynamic(() => import('./fun/OrderPickerEn').then(m => ({ default: m.OrderPickerEn }))),
  'reaction-time-test-en': dynamic(() => import('./fun/ReactionTimeTestEn').then(m => ({ default: m.ReactionTimeTestEn }))),
  'us-lotto-generator-en': dynamic(() => import('./fun/UsLottoGenerator').then(m => ({ default: m.UsLottoGenerator }))),
  'name-compatibility': dynamic(() => import('./fun/NameCompatibility').then(m => ({ default: m.NameCompatibility }))),
  'birthday-compatibility': dynamic(() => import('./fun/BirthdayCompatibility').then(m => ({ default: m.BirthdayCompatibility }))),
  'daily-tarot': dynamic(() => import('./fun/DailyTarot').then(m => ({ default: m.DailyTarot }))),
  'love-calculator-en': dynamic(() => import('./fun/LoveCalculator').then(m => ({ default: m.LoveCalculator }))),
  'ship-name-generator-en': dynamic(() => import('./fun/ShipNameGenerator').then(m => ({ default: m.ShipNameGenerator }))),
  'daily-horoscope-en': dynamic(() => import('./fun/DailyHoroscope').then(m => ({ default: m.DailyHoroscope }))),
  'personality-color-quiz-en': dynamic(() => import('./fun/PersonalityColorQuiz').then(m => ({ default: m.PersonalityColorQuiz }))),
  'tip-calculator-en': dynamic(() => import('./calculator/TipCalculator').then(m => ({ default: m.TipCalculator }))),
  'gpa-calculator-en': dynamic(() => import('./calculator/GpaCalculator').then(m => ({ default: m.GpaCalculator }))),
  'shell-game': dynamic(() => import('./fun/ShellGame').then(m => ({ default: m.ShellGame }))),
  'shell-game-en': dynamic(() => import('./fun/ShellGameEn').then(m => ({ default: m.ShellGameEn }))),
  'letter-qr': dynamic(() => import('./fun/LetterQr').then(m => ({ default: m.LetterQr }))),
  'letter-qr-en': dynamic(() => import('./fun/LetterQrEn').then(m => ({ default: m.LetterQrEn }))),
  'saju-reading': dynamic(() => import('./fun/SajuReading').then(m => ({ default: m.SajuReading }))),
  'saju-compatibility': dynamic(() => import('./fun/SajuCompatibility').then(m => ({ default: m.SajuCompatibility }))),
  'team-picker': dynamic(() => import('./fun/TeamPicker').then(m => ({ default: m.TeamPicker }))),
  'team-picker-en': dynamic(() => import('./fun/TeamPickerEn').then(m => ({ default: m.TeamPickerEn }))),
  'typing-game': dynamic(() => import('./fun/TypingGame').then(m => ({ default: m.TypingGame }))),
  'typing-practice': dynamic(() => import('./fun/TypingPractice').then(m => ({ default: m.TypingPractice }))),
  'typing-game-en': dynamic(() => import('./fun/TypingGameEn').then(m => ({ default: m.TypingGameEn }))),
  'typing-practice-en': dynamic(() => import('./fun/TypingPracticeEn').then(m => ({ default: m.TypingPracticeEn }))),
  'number-guess': dynamic(() => import('./fun/NumberGuess').then(m => ({ default: m.NumberGuess }))),
  'number-guess-en': dynamic(() => import('./fun/NumberGuessEn').then(m => ({ default: m.NumberGuessEn }))),
  'password-strength': dynamic(() => import('./calculator/PasswordStrength').then(m => ({ default: m.PasswordStrength }))),
  'password-strength-en': dynamic(() => import('./calculator/PasswordStrengthEn').then(m => ({ default: m.PasswordStrengthEn }))),
  'invoice-generator': dynamic(() => import('./calculator/InvoiceGenerator').then(m => ({ default: m.InvoiceGenerator }))),
  'invoice-generator-en': dynamic(() => import('./calculator/InvoiceGeneratorEn').then(m => ({ default: m.InvoiceGeneratorEn }))),
  'screen-ruler': dynamic(() => import('./calculator/ScreenRuler').then(m => ({ default: m.ScreenRuler }))),
  'screen-ruler-en': dynamic(() => import('./calculator/ScreenRulerEn').then(m => ({ default: m.ScreenRulerEn }))),
  'pomodoro-timer': dynamic(() => import('./calculator/PomodoroTimer').then(m => ({ default: m.PomodoroTimer }))),
  'pomodoro-timer-en': dynamic(() => import('./calculator/PomodoroTimerEn').then(m => ({ default: m.PomodoroTimerEn }))),

  // 추천
  'menu-recommender': dynamic(() => import('./recommender/MenuRecommender').then(m => ({ default: m.MenuRecommender }))),
  'weekend-recommender': dynamic(() => import('./recommender/WeekendRecommender').then(m => ({ default: m.WeekendRecommender }))),
  'rest-recommender': dynamic(() => import('./recommender/RestRecommender').then(m => ({ default: m.RestRecommender }))),
};

/**
 * 슬러그로 도구 컴포넌트 가져오기
 */
export function getToolComponent(slug: string): ComponentType | undefined {
  return toolComponents[slug];
}

/**
 * 등록된 도구 목록 가져오기
 */
export function getRegisteredTools(): string[] {
  return Object.keys(toolComponents);
}
